### ISSUE TITLE
Implement negation on `HumanRegex<SymbolChain>`

### ISSUE THREAD

**Issue by PacificBird** [cmccomb/human_regex#13]
Out of all the operations that can be done on regular languages, finding the complement is definitely the most difficult (or at least the least obvious). I think having one that doesn't rely on runtime lookarounds (which technically make regular expressions _not_ regular, and aren't supported by the Regex crate anyways) would be an extremely unique feature that I'm not sure if any other Regex library out there has.

**Comment by cmccomb** [comment]
I just came across [regex_syntax](https://docs.rs/regex-syntax/latest/regex_syntax/). I wonder if the AST associated with the regex of a `HumanRegex<SymbolChain>` would be useful for finding the complement?

**Comment by PacificBird** [comment]
Okay with some more research and thought I think this is generally a bad idea. Computing the complement of an arbitrary regular expression can take a _long_ and unpredictable amount of time. For certain unambiguous forms, they can be bounded to polynomial time (see [here](https://arxiv.org/abs/0802.2869)), but it goes against the general "anyone can regex" nature of the library to require everyone to know what a one-unambiguous regular expression is (much less how to ensure their expressions are such at runtime) before they're able to properly use the complement operator. Also, it would take a good deal of work to implement the feature for something that would be rarely useful, unpredictable at runtime, and difficult for most people to understand, so I'm going to close this one.
