### ISSUE TITLE
Thanks you for the inspiration

### ISSUE THREAD

**Issue by GroophyLifefor** [cmccomb/human_regex#15]
I would have preferred to post this in a discussion section but it is not open in this repo.

I'm totally regex illiterate and I started a project thinking I'd learn a little while trying to build the library, I made a simplified project by adding the easy parts and I left the credit.

I made this project in C#, but I paid attention to the syntax being similar, congratulations on your project.

https://github.com/GroophyLifefor/HumanRegex.NET

**Comment by cmccomb** [comment]
I'm still pretty regex illiterate too :-) Thanks for sharing your project!
