### ISSUE TITLE
Adding negation?

### ISSUE THREAD

**Issue by max-ishere** [cmccomb/human_regex#7]
One way would be to do this would be to return a unit struct from some functions and overload the `!` operator. This should not break current API. You can also make the + operator convert the type to string immediately. E.g:

```rust
fn add<T: Into<String>>(_: T) -> Self {}
```

### Intended usage:
```rust
let regex = hex() + !digit();
```

**Comment by cmccomb** [comment]
Will work on this! Great idea!

**Comment by PacificBird** [comment]
Unified negation was added with the new type system, both `not()` and `!` should work on everything but arbitrary symbol combinations as of now!
